# Supabase Configuration File
# This file controls various settings for the Supabase project

# Edge Functions Configuration
# Disable JWT verification for functions that need to process queues automatically

[functions.generate-user-embeddings-v2]
verify_jwt = false

[functions.process-embedding-queue]
verify_jwt = false

# Disable JWT verification for recommendation functions to fix frontend integration
[functions.simplified-recommendations]
verify_jwt = false

[functions.enhanced-weighted-recommendations]
verify_jwt = false

[functions.test-enhanced-recommendations]
verify_jwt = false

[functions.get-recommendations-diagnostic]
verify_jwt = false



[functions.generate-match-embeddings]
verify_jwt = false
