# Supabase Configuration File
# This file controls various settings for the Supabase project

# Edge Functions Configuration
# Disable JWT verification for functions that need to process queues automatically

# New V3 Vector Generation Functions
[functions.generate-user-vectors-v3]
verify_jwt = false

[functions.generate-match-vectors-v3]
verify_jwt = false

# Disable JWT verification for recommendation functions to fix frontend integration
[functions.simplified-recommendations]
verify_jwt = false

# Content Moderation Function with ML Integration
[functions.moderate-match-content]
verify_jwt = false
